const countries = [
  {
    code: "AF",
    name: { en: "Afghanistan" },
    dial_code: "+93",
    currency: "AFN",
    subunits: 100,
  },
  {
    code: "AL",
    name: { en: "Albania" },
    dial_code: "+355",
    currency: "ALL",
    subunits: 100,
  },
  {
    code: "DZ",
    name: { en: "Algeria" },
    dial_code: "+213",
    currency: "DZD",
    subunits: 100,
  },
  {
    code: "AS",
    name: { en: "American Samoa" },
    dial_code: "+1684",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "AD",
    name: { en: "Andorra" },
    dial_code: "+376",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "AO",
    name: { en: "Angola" },
    dial_code: "+244",
    currency: "AOA",
    subunits: 100,
  },
  {
    code: "AI",
    name: { en: "Anguilla" },
    dial_code: "+1264",
    currency: "XCD",
    subunits: 100,
  },
  {
    code: "AG",
    name: { en: "Antigua and Barbuda" },
    dial_code: "+1268",
    currency: "XCD",
    subunits: 100,
  },
  {
    code: "AR",
    name: { en: "Argentina" },
    dial_code: "+54",
    currency: "ARS",
    subunits: 100,
  },
  {
    code: "AM",
    name: { en: "Armenia" },
    dial_code: "+374",
    currency: "AMD",
    subunits: 100,
  },
  {
    code: "AW",
    name: { en: "Aruba" },
    dial_code: "+297",
    currency: "AWG",
    subunits: 100,
  },
  {
    code: "AU",
    name: { en: "Australia" },
    dial_code: "+61",
    currency: "AUD",
    subunits: 100,
  },
  {
    code: "AT",
    name: { en: "Austria" },
    dial_code: "+43",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "AZ",
    name: { en: "Azerbaijan" },
    dial_code: "+994",
    currency: "AZN",
    subunits: 100,
  },
  {
    code: "BS",
    name: { en: "Bahamas" },
    dial_code: "+1242",
    currency: "BSD",
    subunits: 100,
  },
  {
    code: "BH",
    name: { en: "Bahrain" },
    dial_code: "+973",
    currency: "BHD",
    subunits: 1000,
  },
  {
    code: "BD",
    name: { en: "Bangladesh" },
    dial_code: "+880",
    currency: "BDT",
    subunits: 100,
  },
  {
    code: "BB",
    name: { en: "Barbados" },
    dial_code: "+1246",
    currency: "BBD",
    subunits: 100,
  },
  {
    code: "BY",
    name: { en: "Belarus" },
    dial_code: "+375",
    currency: "BYN",
    subunits: 100,
  },
  {
    code: "BE",
    name: { en: "Belgium" },
    dial_code: "+32",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "BZ",
    name: { en: "Belize" },
    dial_code: "+501",
    currency: "BZD",
    subunits: 100,
  },
  {
    code: "BJ",
    name: { en: "Benin" },
    dial_code: "+229",
    currency: "XOF",
    subunits: 100,
  },
  {
    code: "BM",
    name: { en: "Bermuda" },
    dial_code: "+1441",
    currency: "BMD",
    subunits: 100,
  },
  {
    code: "BT",
    name: { en: "Bhutan" },
    dial_code: "+975",
    currency: "BTN",
    subunits: 100,
  },
  {
    code: "BO",
    name: { en: "Bolivia" },
    dial_code: "+591",
    currency: "BOB",
    subunits: 100,
  },
  {
    code: "BA",
    name: { en: "Bosnia and Herzegovina" },
    dial_code: "+387",
    currency: "BAM",
    subunits: 100,
  },
  {
    code: "BW",
    name: { en: "Botswana" },
    dial_code: "+267",
    currency: "BWP",
    subunits: 100,
  },
  {
    code: "BR",
    name: { en: "Brazil" },
    dial_code: "+55",
    currency: "BRL",
    subunits: 100,
  },
  {
    code: "IO",
    name: { en: "British Indian Ocean Territory" },
    dial_code: "+246",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "VG",
    name: { en: "British Virgin Islands" },
    dial_code: "+1284",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "BN",
    name: { en: "Brunei" },
    dial_code: "+673",
    currency: "BND",
    subunits: 100,
  },
  {
    code: "BG",
    name: { en: "Bulgaria" },
    dial_code: "+359",
    currency: "BGN",
    subunits: 100,
  },
  {
    code: "BF",
    name: { en: "Burkina Faso" },
    dial_code: "+226",
    currency: "XOF",
    subunits: 100,
  },
  {
    code: "BI",
    name: { en: "Burundi" },
    dial_code: "+257",
    currency: "BIF",
    subunits: 100,
  },
  {
    code: "KH",
    name: { en: "Cambodia" },
    dial_code: "+855",
    currency: "KHR",
    subunits: 100,
  },
  {
    code: "CM",
    name: { en: "Cameroon" },
    dial_code: "+237",
    currency: "XAF",
    subunits: 100,
  },
  {
    code: "CA",
    name: { en: "Canada" },
    dial_code: "+1",
    currency: "CAD",
    subunits: 100,
  },
  {
    code: "CV",
    name: { en: "Cape Verde" },
    dial_code: "+238",
    currency: "CVE",
    subunits: 100,
  },
  {
    code: "KY",
    name: { en: "Cayman Islands" },
    dial_code: "+1345",
    currency: "KYD",
    subunits: 100,
  },
  {
    code: "CF",
    name: { en: "Central African Republic" },
    dial_code: "+236",
    currency: "XAF",
    subunits: 100,
  },
  {
    code: "TD",
    name: { en: "Chad" },
    dial_code: "+235",
    currency: "XAF",
    subunits: 100,
  },
  {
    code: "CL",
    name: { en: "Chile" },
    dial_code: "+56",
    currency: "CLP",
    subunits: 100,
  },
  {
    code: "CN",
    name: { en: "China" },
    dial_code: "+86",
    currency: "CNY",
    subunits: 100,
  },
  {
    code: "CX",
    name: { en: "Christmas Island" },
    dial_code: "+61",
    currency: "AUD",
    subunits: 100,
  },
  {
    code: "CC",
    name: { en: "Cocos (Keeling) Islands" },
    dial_code: "+61",
    currency: "AUD",
    subunits: 100,
  },
  {
    code: "CO",
    name: { en: "Colombia" },
    dial_code: "+57",
    currency: "COP",
    subunits: 100,
  },
  {
    code: "KM",
    name: { en: "Comoros" },
    dial_code: "+269",
    currency: "KMF",
    subunits: 100,
  },
  {
    code: "CK",
    name: { en: "Cook Islands" },
    dial_code: "+682",
    currency: "NZD",
    subunits: 100,
  },
  {
    code: "CR",
    name: { en: "Costa Rica" },
    dial_code: "+506",
    currency: "CRC",
    subunits: 100,
  },
  {
    code: "HR",
    name: { en: "Croatia" },
    dial_code: "+385",
    currency: "HRK",
    subunits: 100,
  },
  {
    code: "CU",
    name: { en: "Cuba" },
    dial_code: "+53",
    currency: "CUP",
    subunits: 100,
  },
  {
    code: "CW",
    name: { en: "Curaçao" },
    dial_code: "+599",
    currency: "ANG",
    subunits: 100,
  },
  {
    code: "CY",
    name: { en: "Cyprus" },
    dial_code: "+357",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "CZ",
    name: { en: "Czech Republic" },
    dial_code: "+420",
    currency: "CZK",
    subunits: 100,
  },
  {
    code: "CD",
    name: { en: "Democratic Republic of the Congo" },
    dial_code: "+243",
    currency: "CDF",
    subunits: 100,
  },
  {
    code: "DK",
    name: { en: "Denmark" },
    dial_code: "+45",
    currency: "DKK",
    subunits: 100,
  },
  {
    code: "DJ",
    name: { en: "Djibouti" },
    dial_code: "+253",
    currency: "DJF",
    subunits: 100,
  },
  {
    code: "DM",
    name: { en: "Dominica" },
    dial_code: "+1767",
    currency: "XCD",
    subunits: 100,
  },
  {
    code: "DO",
    name: { en: "Dominican Republic" },
    dial_code: "+1809",
    currency: "DOP",
    subunits: 100,
  },
  {
    code: "TL",
    name: { en: "East Timor" },
    dial_code: "+670",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "EC",
    name: { en: "Ecuador" },
    dial_code: "+593",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "EG",
    name: { en: "Egypt" },
    dial_code: "+20",
    currency: "EGP",
    subunits: 100,
  },
  {
    code: "SV",
    name: { en: "El Salvador" },
    dial_code: "+503",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "GQ",
    name: { en: "Equatorial Guinea" },
    dial_code: "+240",
    currency: "XAF",
    subunits: 100,
  },
  {
    code: "ER",
    name: { en: "Eritrea" },
    dial_code: "+291",
    currency: "ERN",
    subunits: 100,
  },
  {
    code: "EE",
    name: { en: "Estonia" },
    dial_code: "+372",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "ET",
    name: { en: "Ethiopia" },
    dial_code: "+251",
    currency: "ETB",
    subunits: 100,
  },
  {
    code: "FK",
    name: { en: "Falkland Islands" },
    dial_code: "+500",
    currency: "FKP",
    subunits: 100,
  },
  {
    code: "FO",
    name: { en: "Faroe Islands" },
    dial_code: "+298",
    currency: "DKK",
    subunits: 100,
  },
  {
    code: "FJ",
    name: { en: "Fiji" },
    dial_code: "+679",
    currency: "FJD",
    subunits: 100,
  },
  {
    code: "FI",
    name: { en: "Finland" },
    dial_code: "+358",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "FR",
    name: { en: "France" },
    dial_code: "+33",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "PF",
    name: { en: "French Polynesia" },
    dial_code: "+689",
    currency: "XPF",
    subunits: 100,
  },
  {
    code: "GA",
    name: { en: "Gabon" },
    dial_code: "+241",
    currency: "XAF",
    subunits: 100,
  },
  {
    code: "GM",
    name: { en: "Gambia" },
    dial_code: "+220",
    currency: "GMD",
    subunits: 100,
  },
  {
    code: "GE",
    name: { en: "Georgia" },
    dial_code: "+995",
    currency: "GEL",
    subunits: 100,
  },
  {
    code: "DE",
    name: { en: "Germany" },
    dial_code: "+49",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "GH",
    name: { en: "Ghana" },
    dial_code: "+233",
    currency: "GHS",
    subunits: 100,
  },
  {
    code: "GI",
    name: { en: "Gibraltar" },
    dial_code: "+350",
    currency: "GIP",
    subunits: 100,
  },
  {
    code: "GR",
    name: { en: "Greece" },
    dial_code: "+30",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "GL",
    name: { en: "Greenland" },
    dial_code: "+299",
    currency: "DKK",
    subunits: 100,
  },
  {
    code: "GD",
    name: { en: "Grenada" },
    dial_code: "+1473",
    currency: "XCD",
    subunits: 100,
  },
  {
    code: "GU",
    name: { en: "Guam" },
    dial_code: "+1671",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "GT",
    name: { en: "Guatemala" },
    dial_code: "+502",
    currency: "GTQ",
    subunits: 100,
  },
  {
    code: "GG",
    name: { en: "Guernsey" },
    dial_code: "+44",
    currency: "GBP",
    subunits: 100,
  },
  {
    code: "GN",
    name: { en: "Guinea" },
    dial_code: "+224",
    currency: "GNF",
    subunits: 100,
  },
  {
    code: "GW",
    name: { en: "Guinea-Bissau" },
    dial_code: "+245",
    currency: "XOF",
    subunits: 100,
  },
  {
    code: "GY",
    name: { en: "Guyana" },
    dial_code: "+592",
    currency: "GYD",
    subunits: 100,
  },
  {
    code: "HT",
    name: { en: "Haiti" },
    dial_code: "+509",
    currency: "HTG",
    subunits: 100,
  },
  {
    code: "HN",
    name: { en: "Honduras" },
    dial_code: "+504",
    currency: "HNL",
    subunits: 100,
  },
  {
    code: "HK",
    name: { en: "Hong Kong" },
    dial_code: "+852",
    currency: "HKD",
    subunits: 100,
  },
  {
    code: "HU",
    name: { en: "Hungary" },
    dial_code: "+36",
    currency: "HUF",
    subunits: 100,
  },
  {
    code: "IS",
    name: { en: "Iceland" },
    dial_code: "+354",
    currency: "ISK",
    subunits: 100,
  },
  {
    code: "IN",
    name: { en: "India" },
    dial_code: "+91",
    currency: "INR",
    subunits: 100,
  },
  {
    code: "ID",
    name: { en: "Indonesia" },
    dial_code: "+62",
    currency: "IDR",
    subunits: 100,
  },
  {
    code: "IR",
    name: { en: "Iran" },
    dial_code: "+98",
    currency: "IRR",
    subunits: 100,
  },
  {
    code: "IQ",
    name: { en: "Iraq" },
    dial_code: "+964",
    currency: "IQD",
    subunits: 100,
  },
  {
    code: "IE",
    name: { en: "Ireland" },
    dial_code: "+353",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "IM",
    name: { en: "Isle of Man" },
    dial_code: "+44",
    currency: "GBP",
    subunits: 100,
  },
  {
    code: "IL",
    name: { en: "Israel" },
    dial_code: "+972",
    currency: "ILS",
    subunits: 100,
  },
  {
    code: "IT",
    name: { en: "Italy" },
    dial_code: "+39",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "CI",
    name: { en: "Ivory Coast" },
    dial_code: "+225",
    currency: "XOF",
    subunits: 100,
  },
  {
    code: "JM",
    name: { en: "Jamaica" },
    dial_code: "+1876",
    currency: "JMD",
    subunits: 100,
  },
  {
    code: "JP",
    name: { en: "Japan" },
    dial_code: "+81",
    currency: "JPY",
    subunits: 1,
  },
  {
    code: "JE",
    name: { en: "Jersey" },
    dial_code: "+44",
    currency: "GBP",
    subunits: 100,
  },
  {
    code: "JO",
    name: { en: "Jordan" },
    dial_code: "+962",
    currency: "JOD",
    subunits: 100,
  },
  {
    code: "KZ",
    name: { en: "Kazakhstan" },
    dial_code: "+7",
    currency: "KZT",
    subunits: 100,
  },
  {
    code: "KE",
    name: { en: "Kenya" },
    dial_code: "+254",
    currency: "KES",
    subunits: 100,
  },
  {
    code: "KI",
    name: { en: "Kiribati" },
    dial_code: "+686",
    currency: "AUD",
    subunits: 100,
  },
  {
    code: "KW",
    name: { en: "Kuwait" },
    dial_code: "+965",
    currency: "KWD",
    subunits: 1000,
  },
  {
    code: "KG",
    name: { en: "Kyrgyzstan" },
    dial_code: "+996",
    currency: "KGS",
    subunits: 100,
  },
  {
    code: "LA",
    name: { en: "Laos" },
    dial_code: "+856",
    currency: "LAK",
    subunits: 100,
  },
  {
    code: "LV",
    name: { en: "Latvia" },
    dial_code: "+371",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "LB",
    name: { en: "Lebanon" },
    dial_code: "+961",
    currency: "LBP",
    subunits: 100,
  },
  {
    code: "LS",
    name: { en: "Lesotho" },
    dial_code: "+266",
    currency: "LSL",
    subunits: 100,
  },
  {
    code: "LR",
    name: { en: "Liberia" },
    dial_code: "+231",
    currency: "LRD",
    subunits: 100,
  },
  {
    code: "LY",
    name: { en: "Libya" },
    dial_code: "+218",
    currency: "LYD",
    subunits: 1000,
  },
  {
    code: "LI",
    name: { en: "Liechtenstein" },
    dial_code: "+423",
    currency: "CHF",
    subunits: 100,
  },
  {
    code: "LT",
    name: { en: "Lithuania" },
    dial_code: "+370",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "LU",
    name: { en: "Luxembourg" },
    dial_code: "+352",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "MO",
    name: { en: "Macau" },
    dial_code: "+853",
    currency: "MOP",
    subunits: 100,
  },
  {
    code: "MK",
    name: { en: "Macedonia" },
    dial_code: "+389",
    currency: "MKD",
    subunits: 100,
  },
  {
    code: "MG",
    name: { en: "Madagascar" },
    dial_code: "+261",
    currency: "MGA",
    subunits: 100,
  },
  {
    code: "MW",
    name: { en: "Malawi" },
    dial_code: "+265",
    currency: "MWK",
    subunits: 100,
  },
  {
    code: "MY",
    name: { en: "Malaysia" },
    dial_code: "+60",
    currency: "MYR",
    subunits: 100,
  },
  {
    code: "MV",
    name: { en: "Maldives" },
    dial_code: "+960",
    currency: "MVR",
    subunits: 100,
  },
  {
    code: "ML",
    name: { en: "Mali" },
    dial_code: "+223",
    currency: "XOF",
    subunits: 100,
  },
  {
    code: "MT",
    name: { en: "Malta" },
    dial_code: "+356",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "MH",
    name: { en: "Marshall Islands" },
    dial_code: "+692",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "MR",
    name: { en: "Mauritania" },
    dial_code: "+222",
    currency: "MRU",
    subunits: 5,
  },
  {
    code: "MU",
    name: { en: "Mauritius" },
    dial_code: "+230",
    currency: "MUR",
    subunits: 100,
  },
  {
    code: "YT",
    name: { en: "Mayotte" },
    dial_code: "+262",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "MX",
    name: { en: "Mexico" },
    dial_code: "+52",
    currency: "MXN",
    subunits: 100,
  },
  {
    code: "FM",
    name: { en: "Micronesia" },
    dial_code: "+691",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "MD",
    name: { en: "Moldova" },
    dial_code: "+373",
    currency: "MDL",
    subunits: 100,
  },
  {
    code: "MC",
    name: { en: "Monaco" },
    dial_code: "+377",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "MN",
    name: { en: "Mongolia" },
    dial_code: "+976",
    currency: "MNT",
    subunits: 100,
  },
  {
    code: "ME",
    name: { en: "Montenegro" },
    dial_code: "+382",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "MS",
    name: { en: "Montserrat" },
    dial_code: "+1664",
    currency: "XCD",
    subunits: 100,
  },
  {
    code: "MA",
    name: { en: "Morocco" },
    dial_code: "+212",
    currency: "MAD",
    subunits: 100,
  },
  {
    code: "MZ",
    name: { en: "Mozambique" },
    dial_code: "+258",
    currency: "MZN",
    subunits: 100,
  },
  {
    code: "MM",
    name: { en: "Myanmar" },
    dial_code: "+95",
    currency: "MMK",
    subunits: 100,
  },
  {
    code: "NA",
    name: { en: "Namibia" },
    dial_code: "+264",
    currency: "NAD",
    subunits: 100,
  },
  {
    code: "NR",
    name: { en: "Nauru" },
    dial_code: "+674",
    currency: "AUD",
    subunits: 100,
  },
  {
    code: "NP",
    name: { en: "Nepal" },
    dial_code: "+977",
    currency: "NPR",
    subunits: 100,
  },
  {
    code: "NL",
    name: { en: "Netherlands" },
    dial_code: "+31",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "NC",
    name: { en: "New Caledonia" },
    dial_code: "+687",
    currency: "XPF",
    subunits: 100,
  },
  {
    code: "NZ",
    name: { en: "New Zealand" },
    dial_code: "+64",
    currency: "NZD",
    subunits: 100,
  },
  {
    code: "NI",
    name: { en: "Nicaragua" },
    dial_code: "+505",
    currency: "NIO",
    subunits: 100,
  },
  {
    code: "NE",
    name: { en: "Niger" },
    dial_code: "+227",
    currency: "XOF",
    subunits: 100,
  },
  {
    code: "NG",
    name: { en: "Nigeria" },
    dial_code: "+234",
    currency: "NGN",
    subunits: 100,
  },
  {
    code: "NU",
    name: { en: "Niue" },
    dial_code: "+683",
    currency: "NZD",
    subunits: 100,
  },
  {
    code: "NF",
    name: { en: "Norfolk Island" },
    dial_code: "+672",
    currency: "AUD",
    subunits: 100,
  },
  {
    code: "KP",
    name: { en: "North Korea" },
    dial_code: "+850",
    currency: "KPW",
    subunits: 100,
  },
  {
    code: "MP",
    name: { en: "Northern Mariana Islands" },
    dial_code: "+1670",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "NO",
    name: { en: "Norway" },
    dial_code: "+47",
    currency: "NOK",
    subunits: 100,
  },
  {
    code: "OM",
    name: { en: "Oman" },
    dial_code: "+968",
    currency: "OMR",
    subunits: 1000,
  },
  {
    code: "PK",
    name: { en: "Pakistan" },
    dial_code: "+92",
    currency: "PKR",
    subunits: 100,
  },
  {
    code: "PW",
    name: { en: "Palau" },
    dial_code: "+680",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "PS",
    name: { en: "Palestine" },
    dial_code: "+970",
    currency: "ILS",
    subunits: 100,
  },
  {
    code: "PA",
    name: { en: "Panama" },
    dial_code: "+507",
    currency: "PAB",
    subunits: 100,
  },
  {
    code: "PG",
    name: { en: "Papua New Guinea" },
    dial_code: "+675",
    currency: "PGK",
    subunits: 100,
  },
  {
    code: "PY",
    name: { en: "Paraguay" },
    dial_code: "+595",
    currency: "PYG",
    subunits: 100,
  },
  {
    code: "PE",
    name: { en: "Peru" },
    dial_code: "+51",
    currency: "PEN",
    subunits: 100,
  },
  {
    code: "PH",
    name: { en: "Philippines" },
    dial_code: "+63",
    currency: "PHP",
    subunits: 100,
  },
  {
    code: "PL",
    name: { en: "Poland" },
    dial_code: "+48",
    currency: "PLN",
    subunits: 100,
  },
  {
    code: "PT",
    name: { en: "Portugal" },
    dial_code: "+351",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "PR",
    name: { en: "Puerto Rico" },
    dial_code: "+1",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "QA",
    name: { en: "Qatar" },
    dial_code: "+974",
    currency: "QAR",
    subunits: 100,
  },
  {
    code: "RE",
    name: { en: "Réunion" },
    dial_code: "+262",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "RO",
    name: { en: "Romania" },
    dial_code: "+40",
    currency: "RON",
    subunits: 100,
  },
  {
    code: "RU",
    name: { en: "Russia" },
    dial_code: "+7",
    currency: "RUB",
    subunits: 100,
  },
  {
    code: "RW",
    name: { en: "Rwanda" },
    dial_code: "+250",
    currency: "RWF",
    subunits: 100,
  },
  {
    code: "BL",
    name: { en: "Saint Barthélemy" },
    dial_code: "+590",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "SH",
    name: { en: "Saint Helena" },
    dial_code: "+290",
    currency: "SHP",
    subunits: 100,
  },
  {
    code: "KN",
    name: { en: "Saint Kitts and Nevis" },
    dial_code: "+1869",
    currency: "XCD",
    subunits: 100,
  },
  {
    code: "LC",
    name: { en: "Saint Lucia" },
    dial_code: "+1758",
    currency: "XCD",
    subunits: 100,
  },
  {
    code: "MF",
    name: { en: "Saint Martin" },
    dial_code: "+590",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "PM",
    name: { en: "Saint Pierre and Miquelon" },
    dial_code: "+508",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "VC",
    name: { en: "Saint Vincent and the Grenadines" },
    dial_code: "+1784",
    currency: "XCD",
    subunits: 100,
  },
  {
    code: "WS",
    name: { en: "Samoa" },
    dial_code: "+685",
    currency: "WST",
    subunits: 100,
  },
  {
    code: "SM",
    name: { en: "San Marino" },
    dial_code: "+378",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "ST",
    name: { en: "São Tomé and Príncipe" },
    dial_code: "+239",
    currency: "STN",
    subunits: 100,
  },
  {
    code: "SA",
    name: { en: "Saudi Arabia" },
    dial_code: "+966",
    currency: "SAR",
    subunits: 100,
  },
  {
    code: "SN",
    name: { en: "Senegal" },
    dial_code: "+221",
    currency: "XOF",
    subunits: 100,
  },
  {
    code: "RS",
    name: { en: "Serbia" },
    dial_code: "+381",
    currency: "RSD",
    subunits: 100,
  },
  {
    code: "SC",
    name: { en: "Seychelles" },
    dial_code: "+248",
    currency: "SCR",
    subunits: 100,
  },
  {
    code: "SL",
    name: { en: "Sierra Leone" },
    dial_code: "+232",
    currency: "SLL",
    subunits: 100,
  },
  {
    code: "SG",
    name: { en: "Singapore" },
    dial_code: "+65",
    currency: "SGD",
    subunits: 100,
  },
  {
    code: "SX",
    name: { en: "Sint Maarten" },
    dial_code: "+1721",
    currency: "ANG",
    subunits: 100,
  },
  {
    code: "SK",
    name: { en: "Slovakia" },
    dial_code: "+421",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "SI",
    name: { en: "Slovenia" },
    dial_code: "+386",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "SB",
    name: { en: "Solomon Islands" },
    dial_code: "+677",
    currency: "SBD",
    subunits: 100,
  },
  {
    code: "SO",
    name: { en: "Somalia" },
    dial_code: "+252",
    currency: "SOS",
    subunits: 100,
  },
  {
    code: "ZA",
    name: { en: "South Africa" },
    dial_code: "+27",
    currency: "ZAR",
    subunits: 100,
  },
  {
    code: "KR",
    name: { en: "South Korea" },
    dial_code: "+82",
    currency: "KRW",
    subunits: 1,
  },
  {
    code: "SS",
    name: { en: "South Sudan" },
    dial_code: "+211",
    currency: "SSP",
    subunits: 100,
  },
  {
    code: "ES",
    name: { en: "Spain" },
    dial_code: "+34",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "LK",
    name: { en: "Sri Lanka" },
    dial_code: "+94",
    currency: "LKR",
    subunits: 100,
  },
  {
    code: "SD",
    name: { en: "Sudan" },
    dial_code: "+249",
    currency: "SDG",
    subunits: 100,
  },
  {
    code: "SR",
    name: { en: "Suriname" },
    dial_code: "+597",
    currency: "SRD",
    subunits: 100,
  },
  {
    code: "SJ",
    name: { en: "Svalbard and Jan Mayen" },
    dial_code: "+47",
    currency: "NOK",
    subunits: 100,
  },
  {
    code: "SZ",
    name: { en: "Swaziland" },
    dial_code: "+268",
    currency: "SZL",
    subunits: 100,
  },
  {
    code: "SE",
    name: { en: "Sweden" },
    dial_code: "+46",
    currency: "SEK",
    subunits: 100,
  },
  {
    code: "CH",
    name: { en: "Switzerland" },
    dial_code: "+41",
    currency: "CHF",
    subunits: 100,
  },
  {
    code: "SY",
    name: { en: "Syria" },
    dial_code: "+963",
    currency: "SYP",
    subunits: 100,
  },
  {
    code: "TW",
    name: { en: "Taiwan" },
    dial_code: "+886",
    currency: "TWD",
    subunits: 100,
  },
  {
    code: "TJ",
    name: { en: "Tajikistan" },
    dial_code: "+992",
    currency: "TJS",
    subunits: 100,
  },
  {
    code: "TZ",
    name: { en: "Tanzania" },
    dial_code: "+255",
    currency: "TZS",
    subunits: 100,
  },
  {
    code: "TH",
    name: { en: "Thailand" },
    dial_code: "+66",
    currency: "THB",
    subunits: 100,
  },
  {
    code: "TG",
    name: { en: "Togo" },
    dial_code: "+228",
    currency: "XOF",
    subunits: 100,
  },
  {
    code: "TK",
    name: { en: "Tokelau" },
    dial_code: "+690",
    currency: "NZD",
    subunits: 100,
  },
  {
    code: "TO",
    name: { en: "Tonga" },
    dial_code: "+676",
    currency: "TOP",
    subunits: 100,
  },
  {
    code: "TT",
    name: { en: "Trinidad and Tobago" },
    dial_code: "+1868",
    currency: "TTD",
    subunits: 100,
  },
  {
    code: "TN",
    name: { en: "Tunisia" },
    dial_code: "+216",
    currency: "TND",
    subunits: 1000,
  },
  {
    code: "TR",
    name: { en: "Turkey" },
    dial_code: "+90",
    currency: "TRY",
    subunits: 100,
  },
  {
    code: "TM",
    name: { en: "Turkmenistan" },
    dial_code: "+993",
    currency: "TMT",
    subunits: 100,
  },
  {
    code: "TC",
    name: { en: "Turks and Caicos Islands" },
    dial_code: "+1649",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "TV",
    name: { en: "Tuvalu" },
    dial_code: "+688",
    currency: "AUD",
    subunits: 100,
  },
  {
    code: "VI",
    name: { en: "U.S. Virgin Islands" },
    dial_code: "+1340",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "UG",
    name: { en: "Uganda" },
    dial_code: "+256",
    currency: "UGX",
    subunits: 100,
  },
  {
    code: "UA",
    name: { en: "Ukraine" },
    dial_code: "+380",
    currency: "UAH",
    subunits: 100,
  },
  {
    code: "AE",
    name: { en: "United Arab Emirates" },
    dial_code: "+971",
    currency: "AED",
    subunits: 100,
  },
  {
    code: "GB",
    name: { en: "United Kingdom" },
    dial_code: "+44",
    currency: "GBP",
    subunits: 100,
  },
  {
    code: "US",
    name: { en: "United States" },
    dial_code: "+1",
    currency: "USD",
    subunits: 100,
  },
  {
    code: "UY",
    name: { en: "Uruguay" },
    dial_code: "+598",
    currency: "UYU",
    subunits: 100,
  },
  {
    code: "UZ",
    name: { en: "Uzbekistan" },
    dial_code: "+998",
    currency: "UZS",
    subunits: 100,
  },
  {
    code: "VU",
    name: { en: "Vanuatu" },
    dial_code: "+678",
    currency: "VUV",
    subunits: 1,
  },
  {
    code: "VA",
    name: { en: "Vatican" },
    dial_code: "+379",
    currency: "EUR",
    subunits: 100,
  },
  {
    code: "VE",
    name: { en: "Venezuela" },
    dial_code: "+58",
    currency: "VES",
    subunits: 100,
  },
  {
    code: "VN",
    name: { en: "Vietnam" },
    dial_code: "+84",
    currency: "VND",
    subunits: 10,
  },
  {
    code: "WF",
    name: { en: "Wallis and Futuna" },
    dial_code: "+681",
    currency: "XPF",
    subunits: 100,
  },
  {
    code: "EH",
    name: { en: "Western Sahara" },
    dial_code: "+212",
    currency: "MAD",
    subunits: 100,
  },
  {
    code: "YE",
    name: { en: "Yemen" },
    dial_code: "+967",
    currency: "YER",
    subunits: 100,
  },
  {
    code: "ZM",
    name: { en: "Zambia" },
    dial_code: "+260",
    currency: "ZMW",
    subunits: 100,
  },
  {
    code: "ZW",
    name: { en: "Zimbabwe" },
    dial_code: "+263",
    currency: "ZWL",
    subunits: 100,
  },
];

export default countries;