import {
  Border,
  Color,
  FontFamily,
  FontSize,
  Padding,
} from "../../GlobalStyles";

export const CollabOpenPaymentStyles = {
  container: {
    flex: 1,
    backgroundColor: Color.colorWhite,
    width: "100%",
  },
  innerContainer: {
    alignItems: "center",
    height: "auto",
    paddingHorizontal: Padding.p_base,
  },
  header: {
    marginVertical: Padding.p_xl,
    width: "100%",
  },
  headerText: {
    fontSize: FontSize.size_3xl,
    lineHeight: 28,
    fontFamily: FontFamily.workSansBold,
    color: Color.colorGray_300,
    textAlign: "left",
  },
  subHeader: {
    marginBottom: Padding.p_xl,
    width: "100%",
  },
  subHeaderText: {
    fontSize: FontSize.size_base,
    lineHeight: 24,
    fontFamily: FontFamily.workSansRegular,
    color: Color.colorGray_300,
    textAlign: "left",
  },
  planContainer: {
    width: "100%",
    height: "auto",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    gap: 20,
    flexWrap: "wrap",
  },
  planDetailsContainer: {
    backgroundColor: Color.colorWhite,
    borderStyle: "solid",
    borderColor: "black",
    borderWidth: 2,
    width: 328,
    height: 178,
    padding: Padding.p_5xl,
    borderRadius: Border.br_xs,
    marginVertical: Padding.p_7xs,
  },
  planDuration: {
    fontSize: FontSize.size_base,
    fontWeight: "700",
    fontFamily: FontFamily.workSansBold,
    color: Color.colorGray_300,
    width: "auto",
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  planPrice: {
    fontSize: FontSize.size_17xl,
    letterSpacing: -1,
    lineHeight: 45,
    fontWeight: "900",
    fontFamily: FontFamily.workSansBlack,
    color: Color.colorGray_300,
    marginRight: Padding.p_xs,
  },
  validityContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: Padding.p_base,
  },
  validityHeader: {
    fontSize: FontSize.size_base,
    fontWeight: "700",
    fontFamily: FontFamily.workSansBold,
    color: Color.colorGray_300,
    width: "auto",
  },
  validityText: {
    fontSize: FontSize.size_base,
    fontWeight: "700",
    fontFamily: FontFamily.workSansBold,
    color: Color.colorGray_300,
    width: "auto",
  },
  star: {
    fontSize: FontSize.size_base,
    fontWeight: "700",
    fontFamily: FontFamily.workSansBold,
    color: "red",
    width: "auto",
  },
  require: {
    fontSize: FontSize.size_sm,
    fontWeight: "normal",
    fontFamily: FontFamily.workSansBold,
    color: Color.colorGray_300,
    width: "auto",
  },
  selectPlanButton: {
    backgroundColor: "#F0F2F5",
    borderRadius: 12,
    paddingVertical: Padding.p_base,
    alignItems: "center",
    marginVertical: Padding.p_base,
    width: "100%",
  },
  selectPlanButtonText: {
    color: "black",
    fontSize: FontSize.size_base,
    fontFamily: FontFamily.plusJakartaSansBold,
  },
};
